##  Sensitivity Analysis for Evapotranspiration and Runoff according to the input paramters in the Reynolds Mountain East catchment using pySUMMA

## 1. Introduction

This study is to analyze the sensitivity of input parameters related with spatial paramters on Evapotranspiration and Runoff using a SUMMA model for the Reynolds Mountain East catchment. This study looked at the twelve parameters to analysis the impact on Evapotranspiration and Runoff. 

In this Jupyter Notebook, the pySUMMA library is used to produce this analysis. First, the input parameters are described. Next, the Methods section describes how the pySUMMA can be used to 

 1) Explanation of the study area : the Reynolds Mountain East catchment
 
 2) How to download TestCases from HS and Installation to prepare SUMMA simulation

 3) Creating pySUMMA Simulation Object and setting SUMMA executable
 
 4) Creating Param Trial obejct to read "Param Trial input netcdf file"
 
 5) Running SUMMA with input parameters
 
 6) Creating Text from output netcdf of SUMMA

Collectively, this Jupyter Notebook serves as an example of how hydrologic modeling can be conducted directly within a Jupyter Notebook by leveraging the pySUMMA library. 

## 2. Background 

### The Sensitivity Analysis with the input parameters in SUMMA

In [4]:
#import libraries to display equations within the notebook
from IPython.display import display, Math, Latex

### 1.) Input parameter in para_trial netcdf for SUMMA

 |  Parameters      |  Min       |   Max       |   Step (Max-Min)/10 | Description |
 |:------------------:|------------|-------------|---------------------|:-------------|
 |critSoilTranspire |  0.0       |   1.0       | 0.1                 |  critical vol. liq. water content when transpiration is limited (-)            |  
 |critSoilWilting   |  0.0       |   1.0       | 0.1                 | critical vol. liq. water content when plants are wilting (-)    |
 |k_soil            |  0.0000001 |   0.00001   | 0.00000099          | hydraulic conductivity of soil (m s-1)    |
 |qSurfScale        |  1.0       | 100.0       | 9.9                 | scaling factor in the surface runoff parameterization (-)    |
 |rootDistExp       |  0.01      |   1.0       | 0.099               | exponent controlling the vertical distribution of root density (-)    |
 |summerLAI         |  0.01      |  10.0       | 0.999               | maximum leaf area index at the peak of the growing season (m2 m-2)    |
 |theta_mp          |  0.3       |   0.6       | 0.03                | volumetric liquid water content when macropore flow begins (-)    |
 |theta_res         |  0.001     |   0.1       | 0.0099              | volumetric residual water content (-)    |
 |theta_sat         |  0.3       |   0.6       | 0.03                | porosity (-)    |
 |vGn_alpha         | -1.0       |  -0.01      | 0.099               | van Genuchten "alpha" parameter (m-1)    |
 |vGn_n             |  1.0       |   3.0       | 0.2                 | van Genuchten "n" parameter (-)    |
 |winterSAI         |  0.01      |   3.0       | 0.299               | stem area index prior to the start of the growing season (m2 m-2)    |

## 3. Methods

### 1) Study Area

#### The Reynolds Mountain East catchment is located in southwestern Idaho as shown in the figure below.

In [5]:
from ipyleaflet import Map, GeoJSON
import json

In [6]:
m = Map(center=[43.06745, -116.75489], zoom=15)
with open('reynolds_geojson_latlon.geojson') as f:
    data = json.load(f)
g = GeoJSON(data=data)
m.add_layer(g)
m

Map(basemap={'url': 'https://{s}.tile.openstreetmap.org/{z}/{x}/{y}.png', 'max_zoom': 19, 'attribution': 'Map data (c) <a href="https://openstreetmap.org">OpenStreetMap</a> contributors'}, center=[43.06745, -116.75489], layers=(TileLayer(base=True, max_zoom=19, min_zoom=1, options=['attribution', 'detect_retina', 'max_zoom', 'min_zoom', 'tile_size']), GeoJSON(data={'type': 'FeatureCollection', 'name': 'reynolds_geojson_latlon', 'crs': {'type': 'name', 'properties': {'name': 'urn:ogc:def:crs:OGC:1.3:CRS84'}}, 'features': [{'type': 'Feature', 'properties': {'OBJECTID': 1, 'RCEW_REGIO': 376208.194027, 'PERIMETER': 3340.0, 'RMEAST_MAS': 2, 'RMEAST_M_1': 2, 'GRID_CODE': 1}, 'geometry': {'type': 'Polygon', 'coordinates': [[[-116.7557156288284, 43.07072983625339], [-116.75559279969227, 43.07072957489522], [-116.75559315872648, 43.07063952502811], [-116.75547032977175, 43.07063926353894], [-116.75534750204696, 43.07063900192053], [-116.75522467432737, 43.07063873926983], [-116.7551018453776, 43.07063847738518], [-116.75510220512943, 43.0705484275199], [-116.75497937636112, 43.07054816550426], [-116.75497973629112, 43.070458115638395], [-116.75485690770425, 43.07045785349174], [-116.7547340803473, 43.07045759121584], [-116.754611252992, 43.070457328808125], [-116.75448842441011, 43.07045706626597], [-116.75436559706174, 43.070456802694125], [-116.75424276848315, 43.07045653988829], [-116.75424312949033, 43.070366490025975], [-116.75412030232148, 43.070366227091775], [-116.75399747392602, 43.0703659640231], [-116.75399783529119, 43.07027591416101], [-116.75387500707716, 43.07027565096134], [-116.7537521800931, 43.07027538763253], [-116.75362935188241, 43.07027512416918], [-116.75362971378532, 43.07018507430818], [-116.75363007445833, 43.07009502444305], [-116.75363043635795, 43.07000497457918], [-116.75363079702761, 43.06991492471125], [-116.75375362451547, 43.06991518907176], [-116.75375398500368, 43.06982513920156], [-116.75375434671845, 43.06973508933261], [-116.75375470720336, 43.06964503945952], [-116.75363188147955, 43.06964477600465], [-116.7536322421426, 43.069554726130995], [-116.75350941660027, 43.06955446254514], [-116.75350977744145, 43.06946441267091], [-116.75338695208056, 43.06946414895402], [-116.75338731309988, 43.0693740990792], [-116.75326448792045, 43.06937383523132], [-116.75326485034614, 43.06928378535855], [-116.75314202411995, 43.06928352137701], [-116.75301919912368, 43.069283257266314], [-116.75301956067906, 43.06919320739113], [-116.753019923461, 43.06910315751716], [-116.75289709759774, 43.069102893273666], [-116.7527742729644, 43.06910262890097], [-116.75277463610426, 43.06901257902725], [-116.75265181042415, 43.069012314520926], [-116.75265217374212, 43.06892226464661], [-116.75252934824346, 43.06892200000929], [-116.75252971173958, 43.06883195013435], [-116.7525300740058, 43.0687419002554], [-116.75240725009662, 43.068741635490554], [-116.75240761254095, 43.06865158561097], [-116.75240797621186, 43.06856153573259], [-116.75240833865288, 43.06847148585014], [-116.7524087023168, 43.06838143686942], [-116.75228587790387, 43.06838117107297], [-116.75228624174592, 43.068291122091665], [-116.7522866043617, 43.068201072205795], [-116.75228696820399, 43.06811102232113], [-116.75228733081644, 43.06802097243243], [-116.75228769465541, 43.067930922544896], [-116.75228805726088, 43.067840873553784], [-116.75228842109648, 43.06775082366344], [-116.75216559794013, 43.06775055864152], [-116.75216596195388, 43.06766050875055], [-116.75204313897898, 43.06766024359765], [-116.75192031723756, 43.067659977415076], [-116.7517974954942, 43.067659712001166], [-116.75167467252432, 43.06765944645277], [-116.75167503725551, 43.06756939656374], [-116.75167540075684, 43.067479346670616], [-116.75167576548104, 43.067389297679235], [-116.75167612897903, 43.06729924778324], [-116.75155330795809, 43.067298982109065], [-116.75155367163417, 43.06720893221254], [-116.75155403653679, 43.06711888231719], [-116.7515544002095, 43.06702883241775

### 2) Download TestCases from HS and Installation to prepare SUMMA simulation

In [4]:
# To authenticate using HTTP Basic authentication.
from hs_restclient import HydroShare, HydroShareAuthBasic
hs = HydroShare()

In [1]:
# import utils.py to download TestCases from HS, unzip and installation
from pysumma.utils import utils

In [2]:
# define directory where you save SUMMA TestCases
save_filepath = '/media/sf_pysumma'

In [3]:
# assign resource id of SUMMA TestCases on HS (Now I uploaded SUMMA TestCases in My Resources(status=Private) on HS )
resource_id = 'a0105d479c334764ba84633c5b9c1c01'

In [8]:
# call install_test_cases_hs method to download TestCase from HS, unzip and install the TestCase.
hs_path = utils.install_test_cases_hs(hs, resource_id, save_filepath)

In [10]:
hs_path = '/media/sf_pysumma/a0105d479c334764ba84633c5b9c1c01/a0105d479c334764ba84633c5b9c1c01/data/contents'

### 3) Create pySUMMA Simulation Object and set SUMMA executable

In [11]:
from pysumma.Simulation import Simulation

In [12]:
# create a pySUMMA simulation object using the SUMMA 'file manager' input file 
S = Simulation(hs_path + '/summaTestCases_2.x/settings/wrrPaperTestCases/figure07/summa_fileManager_riparianAspenSimpleResistance.txt')

ModelOuput master file filepath: /media/sf_pysumma/pysumma/sopron_2018_notebooks/var_lookup.f90


In [13]:
S.executable = "/media/sf_pysumma/compile/summa/bin/summa.exe"

In [14]:
# set the simulation start and finish times
S.decision_obj.simulStart.value = "1998-10-01 01:00"
S.decision_obj.simulFinsh.value = "2008-10-01 00:00"

### 4) Create Param Trial obejct to read "Param Trial input netcdf file"

In [15]:
import netCDF4 as nc
import numpy as np

In [16]:
Param_Trial_file = S.setting_path.value + S.para_trial.value
Param_Trial_file1 = Param_Trial_file.replace("/", "//")

In [17]:
Param_Trial = nc.Dataset(Param_Trial_file1,'r+')

In [18]:
Param_Trial

<class 'netCDF4._netCDF4.Dataset'>
root group (NETCDF4 data model, file format HDF5):
    history: Converted to NetCDF using "/Users/nijssen/Dropbox/data/PLUMBER/PLUMBER_data/tools/paramTrial_ascii_to_nc.py --ascii_in summa_zParamTrial_riparianAspen.txt --nc_out summa_zParamTrial_riparianAspen.nc" on 2017-08-30 13:37:17

    dimensions(sizes): hru(1)
    variables(dimensions): float64 hruIndex(hr), float64 frozenPrecipMultip(hr), float64 theta_mp(hr), float64 theta_sat(hr), float64 theta_res(hr), float64 vGn_alpha(hr), float64 vGn_n(hr), float64 f_impede(hr), float64 k_soil(hr), float64 k_macropore(hr), float64 critSoilWilting(hr), float64 critSoilTranspire(hr), float64 winterSAI(hr), float64 summerLAI(hr), float64 heightCanopyTop(hr), float64 heightCanopyBottom(hr), float64 kAnisotropic(hr), float64 rootDistExp(hr), float64 zScale_TOPMODEL(hr), float64 qSurfScale(hr)
    groups: 

### 6) Running SUMMA with input parameters

### 6-1) parameter = rootDistExp

In [19]:
name = 'rootDistExp'

In [20]:
name_value = Param_Trial.variables[name][:]
name_value

array([1.])

In [21]:
min_para = 0.01
max_para = 1
delta = (max_para-min_para)

In [22]:
Param_Trial = nc.Dataset(Param_Trial_file1,'r+')
Param_Trial_file1

'//media//sf_pysumma//a0105d479c334764ba84633c5b9c1c01//a0105d479c334764ba84633c5b9c1c01//data//contents//summaTestCases_2.x//settings//wrrPaperTestCases//figure07//summa_zParamTrial_riparianAspen.nc'

In [18]:
for i in np.arange(min_para, max_para+delta, delta):
    name_value[0] = i
    Param_Trial = nc.Dataset(Param_Trial_file1,'r+')
    Param_Trial.variables[name][:] = name_value
    results_simpleResistance, out_file = S.execute(run_suffix="rootDistExp"+str(i), run_option = 'local')
    Param_Trial.close()
    print (name_value[0])

0.01
0.109
0.20800000000000002
0.30700000000000005
0.406
0.505
0.6040000000000001
0.7030000000000001
0.802
0.901
1.0


### 6-2) parameter = critSoilTranspire (Not Working)

In [17]:
name = 'critSoilTranspire'

In [18]:
name_value = Param_Trial.variables[name][:]
name_value

array([0.2])

In [19]:
min_para = 0
max_para = 1
delta = (max_para-min_para)/10

In [ ]:
for i in np.arange(min_para, max_para+delta, delta):
    name_value[0] = i
    Param_Trial = nc.Dataset(Param_Trial_file1,'r+')
    Param_Trial.variables[name][:] = name_value
    results_simpleResistance, out_file = S.execute(run_suffix="critSoilTranspire"+str(i), run_option = 'local')
    Param_Trial.close()
    print (name_value[0])

### 6-3) parameter = critSoilWilting (Not Working)

In [10]:
name = 'critSoilWilting'

In [11]:
name_value = Param_Trial.variables[name][:]
name_value

array([0.125])

In [12]:
min_para = 0
max_para = 1
delta = (max_para-min_para)/10

In [ ]:
for i in np.arange(min_para, max_para+delta, delta):
    name_value[0] = i
    Param_Trial = nc.Dataset(Param_Trial_file1,'r+')
    Param_Trial.variables[name][:] = name_value
    results_simpleResistance, out_file = S.execute(run_suffix="critSoilWilting"+str(i), run_option = 'local')
    Param_Trial.close()
    print (name_value[0])

### 6-4) parameter = k_soil

In [38]:
name = 'k_soil'

In [39]:
name_value = Param_Trial.variables[name][:]
name_value

array([3.53e-06])

In [40]:
min_para = 0.0000001
max_para = 0.00001
delta = (max_para-min_para)/10

In [47]:
for i in np.arange(min_para, max_para+delta, delta):
    name_value[0] = i
    Param_Trial = nc.Dataset(Param_Trial_file1,'r+')
    Param_Trial.variables[name][:] = name_value
    results_simpleResistance, out_file = S.execute(run_suffix="k_soil"+str(i), run_option = 'local')
    Param_Trial.close()
    print (name_value[0])

1e-07
1.0900000000000002e-06
2.0800000000000004e-06
3.0700000000000007e-06
4.060000000000001e-06
5.050000000000002e-06
6.0400000000000015e-06
7.030000000000001e-06
8.020000000000003e-06
9.010000000000004e-06
1.0000000000000004e-05


### 6-5) parameter = qSurfScale

In [10]:
name = 'qSurfScale'

In [11]:
name_value = Param_Trial.variables[name][:]
name_value

array([84.063])

In [12]:
min_para = 1
max_para = 100
delta = (max_para-min_para)/10

In [15]:
for i in np.arange(min_para, max_para+delta, delta):
    name_value[0] = i
    Param_Trial = nc.Dataset(Param_Trial_file1,'r+')
    Param_Trial.variables[name][:] = name_value
    results_simpleResistance, out_file = S.execute(run_suffix="qSurfScale"+str(i), run_option = 'local')
    Param_Trial.close()
    print (name_value[0])

1.0
12.0
23.0
34.0
45.0
56.0
67.0
78.0
89.0
100.0


### 6-6) parameter = summerLAI

In [10]:
name = 'summerLAI'

In [11]:
name_value = Param_Trial.variables[name][:]
name_value

array([2.5])

In [12]:
min_para = 0.01
max_para = 10
delta = (max_para-min_para)/10

In [15]:
for i in np.arange(min_para, max_para+delta, delta):
    name_value[0] = i
    Param_Trial = nc.Dataset(Param_Trial_file1,'r+')
    Param_Trial.variables[name][:] = name_value
    results_simpleResistance, out_file = S.execute(run_suffix="summerLAI"+str(i), run_option = 'local')
    Param_Trial.close()
    print (name_value[0])

0.01
1.12
2.23
3.34
4.45
5.5600000000000005
6.67
7.78
8.89
10.0


### 6-7) parameter = theta_mp

In [15]:
name = 'theta_mp'

In [ ]:
name_value = Param_Trial.variables[name][:]
name_value

In [43]:
min_para = 0.3
max_para = 0.6
delta = (max_para-min_para)/10

In [20]:
for i in np.arange(min_para, max_para+delta, delta):
    name_value[0] = i
    Param_Trial = nc.Dataset(Param_Trial_file1,'r+')
    Param_Trial.variables[name][:] = name_value
    results_simpleResistance, out_file = S.execute(run_suffix="theta_mp"+str(i), run_option = 'local')
    Param_Trial.close()
    print (name_value[0])

0.3
0.32999999999999996
0.35999999999999993
0.3899999999999999
0.4199999999999999
0.44999999999999984
0.4799999999999998
0.5099999999999998
0.5399999999999998
0.5699999999999997
0.5999999999999996
0.6299999999999997


### 6-7) parameter = theta_res

In [10]:
name = 'theta_res'

In [11]:
name_value = Param_Trial.variables[name][:]
name_value

array([0.1])

In [12]:
min_para = 0.001
max_para = 0.1
delta = (max_para-min_para)/10

In [15]:
for i in np.arange(min_para, max_para+delta, delta):
    name_value[0] = i
    Param_Trial = nc.Dataset(Param_Trial_file1,'r+')
    Param_Trial.variables[name][:] = name_value
    results_simpleResistance, out_file = S.execute(run_suffix="theta_res"+str(i), run_option = 'local')
    Param_Trial.close()
    print (name_value[0])

0.001
0.0109
0.0208
0.030699999999999998
0.0406
0.050499999999999996
0.060399999999999995
0.0703
0.0802
0.09009999999999999
0.09999999999999999


### 6-9) parameter = theta_sat

In [10]:
name = 'theta_sat'

In [11]:
name_value = Param_Trial.variables[name][:]
name_value

array([0.4792])

In [12]:
min_para = 0.3
max_para = 0.6
delta = (max_para-min_para)/10

In [15]:
for i in np.arange(min_para, max_para+delta, delta):
    name_value[0] = i
    Param_Trial = nc.Dataset(Param_Trial_file1,'r+')
    Param_Trial.variables[name][:] = name_value
    results_simpleResistance, out_file = S.execute(run_suffix="theta_sat"+str(i), run_option = 'local')
    Param_Trial.close()
    print (name_value[0])

0.3
0.32999999999999996
0.35999999999999993
0.3899999999999999
0.4199999999999999
0.44999999999999984
0.4799999999999998
0.5099999999999998
0.5399999999999998
0.5699999999999997
0.5999999999999996
0.6299999999999997


### 6-10) parameter = vGn_alpha

In [10]:
name = 'vGn_alpha'

In [11]:
name_value = Param_Trial.variables[name][:]
name_value

array([-0.858])

In [12]:
min_para = -1
max_para = -0.01
delta = (max_para-min_para)/10

In [15]:
for i in np.arange(min_para, max_para+delta, delta):
    name_value[0] = i
    Param_Trial = nc.Dataset(Param_Trial_file1,'r+')
    Param_Trial.variables[name][:] = name_value
    results_simpleResistance, out_file = S.execute(run_suffix="vGn_alpha"+str(i), run_option = 'local')
    Param_Trial.close()
    print (name_value[0])

-1.0
-0.901
-0.802
-0.7030000000000001
-0.6040000000000001
-0.5050000000000001
-0.40600000000000014
-0.30700000000000016
-0.20800000000000018
-0.10900000000000021
-0.010000000000000231


### 6-11) parameter = vGn_n (Not Working)

In [10]:
name = 'vGn_n'

In [11]:
name_value = Param_Trial.variables[name][:]
name_value

array([1.306])

In [12]:
min_para = 1
max_para = 3
delta = (max_para-min_para)/10

In [ ]:
for i in np.arange(min_para, max_para+delta, delta):
    name_value[0] = i
    Param_Trial = nc.Dataset(Param_Trial_file1,'r+')
    Param_Trial.variables[name][:] = name_value
    results_simpleResistance, out_file = S.execute(run_suffix="vGn_n"+str(i), run_option = 'local')
    Param_Trial.close()
    print (name_value[0])

### 6-12) parameter = winterSAI

In [10]:
name = 'winterSAI'

In [11]:
name_value = Param_Trial.variables[name][:]
name_value

array([0.45])

In [12]:
min_para = 0.01
max_para = 3
delta = (max_para-min_para)/10

In [16]:
for i in np.arange(min_para, max_para+delta, delta):
    name_value[0] = i
    Param_Trial = nc.Dataset(Param_Trial_file1,'r+')
    Param_Trial.variables[name][:] = name_value
    results_simpleResistance, out_file = S.execute(run_suffix="winterSAI"+str(i), run_option = 'local')
    Param_Trial.close()
    print (name_value[0])

0.01
0.309
0.608
0.907
1.206
1.505
1.804
2.1029999999999998
2.4019999999999997
2.7009999999999996
2.9999999999999996
3.2989999999999995


### 7) Create Text from output netcdf of SUMMA

In [10]:
from pysumma.Plotting import Plotting
from jupyterthemes import jtplot
import matplotlib.pyplot as plt
import pandas as pd
import os
jtplot.figsize(x=10, y=10)

In [11]:
import glob
aa = glob.glob(hs_path + "/summaTestCases_2.x/output/wrrPaperTestCases/figure07/*.nc")

### 7-1) Create Evapotranspiration Text file from SUMMA output

In [ ]:
for i in range(0,120,1):
    file = aa[i].split('/')[-1]
    output_evap = Plotting(hs_path + '/summaTestCases_2.x/output/wrrPaperTestCases/figure07/'+file)
    sim_scalarCanopyTranspiration = output_evap.ds['scalarCanopyTranspiration']*3600
    sim_scalarCanopyEvaporation = output_evap.ds['scalarCanopyEvaporation']*3600
    sim_scalarGroundEvaporation = output_evap.ds['scalarCanopyTranspiration']*3600
    dates = sim_scalarCanopyTranspiration.coords['time'].data
    scalarCanopyTranspiration = pd.DataFrame(sim_scalarCanopyTranspiration.data, index=dates)
    scalarCanopyEvaporation = pd.DataFrame(sim_scalarCanopyEvaporation.data, index=dates)
    scalarGroundEvaporation = pd.DataFrame(sim_scalarGroundEvaporation.data, index=dates)
    ET_Combine = pd.concat([scalarCanopyTranspiration, scalarCanopyEvaporation, scalarGroundEvaporation], axis=1)
    ET_Combine.columns = ['scalarCanopyTranspiration', 'scalarCanopyEvaporation', 'scalarGroundEvaporation']
    ET_Combine.to_csv('{}.txt'.format(file), sep='\t', index=True)

### 7-2) Create Runoff Text file from SUMMA output

In [ ]:
for i in range(0,120,1):
    file = aa[i].split('/')[-1]
    output_runoff = Plotting(hs_path + '/summaTestCases_2.x/output/wrrPaperTestCases/figure07/'+file)
    sim_runoff = output_runoff.ds['averageInstantRunoff']*86400000
    dates = sim_runoff.coords['time'].data
    sim_runoff_df = pd.DataFrame(sim_runoff.data, index=dates)
    sim_runoff_df.to_csv('{}.txt'.format(file), sep='\t', index=True)